### ISSUE TITLE
TypeError: styled.span is not a function. (In 'styled.span(_templateObject)', 'styled.span' is undefined)

### ISSUE THREAD

**Issue by lmai5** [DJTB/react-furi#2]
## I'm submitting a…

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Support request

## Expected Behavior

React native app should work as usual. 
```
import ReactFuri from 'react-furi';
const MyComponent = () => <ReactFuri word="考え方" reading="かんがえかた" />;
```

## Current Behavior

Console log shows 
```

[Mon Apr 26 2021 01:02:34.811]  ERROR    TypeError: styled.span is not a function. (In 'styled.span(_templateObject)', 'styled.span' is undefined)
[Mon Apr 26 2021 01:02:34.812]  ERROR    Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

![image](https://user-images.githubusercontent.com/6018147/116000516-6b1a3a80-a5a5-11eb-8b60-e38b51adf84a.png)

## Steps to Reproduce (for bugs)

1. Install furi lib using: npm install --save react-furi
2. Install the next required lib: npm i styled-components
3. Start the app using:  npm run ios
4. Console log show the error and the simulator show the errors above.

## Environment

- hatsuon version: npm ls hatsuon
- Node version: hatsuon@1.1.4
- NPM version: 6.14.12
- Yarn version (if you use Yarn): None
- Operating system:  Mac
- Link to your project: N/a

**Comment by lmai5** [comment]
@DJTB Could you help having a look on this issue?

**Comment by DJTB** [comment]
Hey @maihoanglai I'm really sorry I missed these notifications.
I'll try to find some time to publish this with styled components removed and newest react.
