### ISSUE TITLE
Text selections mixes furigana with kanji

### ISSUE THREAD

**Issue by skibitsky** [DJTB/react-furi#5]
<img width="316" alt="Screenshot 2023-01-09 at 10 42@2x" src="https://user-images.githubusercontent.com/15127974/211290257-de45d47a-f59e-4c22-b342-81cbd7d9fe16.png">

## I'm submitting a…

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request

## Expected Behavior

When selecting kanji symbols, only kanji symbols are selected.

## Current Behavior

When copying kanji which has furigana above it, the furigana symbols will be mixed together with kanji.
For example, when I select お見舞い and copy it, my clipboard content is: 
```
お
みま
見舞
い
```

## Possible Solution

Use `user-select: none` for furigana span?

## Steps to Reproduce (for bugs)

1. Open [Demo](https://djtb.github.io/react-furi/) page
2. Try to copy any kanji with uses ReactFuri component and has furi symbols
3. Paste that text somewhere

**Comment by DJTB** [comment]
Thanks for the issue report.
Makes sense that this should be ignored when copying 👍

**Comment by DJTB** [comment]
Thanks for the issue report. Can you provide more details?
The furi span already has `user-select: none;` applied and is not copied (at least on Chrome and Firefox I checked quickly).

**Comment by skibitsky** [comment]
Sorry, I experimented a bit more, and here is what I found.

In Brave when I select お見舞い from the demo page and then paste it somewhere, there are line breaks.
<img width="254" alt="Screenshot 2023-01-11 at 19 44@2x" src="https://user-images.githubusercontent.com/15127974/211902774-9e1f6ee1-b40a-4174-9b96-0581de516d2a.png">

If I copy the same text in Safari, in addition to the line breaks, it adds furigana symbols, even though I didn't select them.
<img width="237" alt="Screenshot 2023-01-11 at 19 46@2x" src="https://user-images.githubusercontent.com/15127974/211903329-8a098dce-d6ec-4501-965b-9342253b7398.png">
Adding `-webkit-user-select: none;` to the fury span didn't help.

In Firefox it works as expected.
<img width="241" alt="Screenshot 2023-01-11 at 19 55@2x" src="https://user-images.githubusercontent.com/15127974/211904872-3edd7120-38b8-4e44-9fc1-50b013209876.png">

**Comment by skibitsky** [comment]
To be honest, I don't know how to make it work in Safari. The `-webkit-user-select: none;` applied to furi span disables selection when only furi is selected. It doesn't make any effect when whole block is selected. 

Selection works well at [jisho.org](https://jisho.org/search/お見舞い). But they store furigana under neighbour span, it isn't nested. It doesn't look as good as your implementation though.
<img width="384" alt="image" src="https://user-images.githubusercontent.com/15127974/211910758-58ee24f1-ba49-4fc0-a5cd-2f044391eebb.png">

**Comment by DJTB** [comment]
Great detail investigating further, though I think this is outside of the scope of this package if Safari and Brave ignore the css.

Any consumers that are displaying text that they expect users may want to copy could either:
a) provide a furigana toggle so users can hide furigana before copying
b) provide a small copy to clipboard button that adds text without furigana
